const MAX_RETRIES = 3;
const SLA_MS = 10_000;
const RETRY_BACKOFF_MS = [2_000, 4_000, 8_000];
const WORKER_POLL_INTERVAL_MS = 2_000;
const STUCK_JOB_THRESHOLD_MS = 2 * 60_000;

module.exports = {
  MAX_RETRIES,
  SLA_MS,
  RETRY_BACKOFF_MS,
  WORKER_POLL_INTERVAL_MS,
  STUCK_JOB_THRESHOLD_MS,
};